### ISSUE TITLE
why - 0.5 in es.py#L83 ?

### ISSUE THREAD

**Issue by joyousrabbit** [openai/evolution-strategies-starter#7]
Hello, why -0.5 in es.py#L83:

def compute_centered_ranks(x):
    y = compute_ranks(x.ravel()).reshape(x.shape).astype(np.float32)
    y /= (x.size - 1)
    y -= .5   # <------ here
    return y

Later, we use  proc_returns_n2[:, 0] - proc_returns_n2[:, 1], so there is no influence of the globel y-=.5, right?

**Comment by PatrykChrabaszcz** [comment]
I think it normalizes ranks to lay between [-0.5, 0.5] . 
I think you are right that it will eventually cancel out later in the code,
but function is called 'compute_**centered**_ranks', so it does that :)

**Comment by joyousrabbit** [comment]
@PatrykChrabaszcz Got it, thanks.
